# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine

# set working directory
WORKDIR /app

# copy package files and ts config
COPY package.json package-lock.json tsconfig.json ./

# install dependencies
RUN npm ci --ignore-scripts

# copy source files
COPY src ./src

# copy other config files
COPY .eslintrc.* .prettierrc.* eslint.config.ts .

# build the project
RUN npm run build

# use non-root user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

# default command
CMD ["node", "dist/server.js"]
